# Generated by Django 5.0.1 on 2024-01-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0002_alter_movements_date_alter_movements_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movements',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movements',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
